name: Deploy Portfolio Live to Namecheap

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Production Sync
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: FTPS Deploy Sync
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftps                   # Explicitly force secure FTPS over port 21
        dangerous-clean-slate: false     # Prevents accidental deletion of unmanaged files
        local-dir: ./                  
        server-dir: ../../public_html/