name: Deploy Portfolio Live to Namecheap

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Production Sync
    runs-on: ubuntu-latest
    
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
    
    - name: FTP Deploy Sync
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21                           # Swapped from 21098 to standard FTP port 21
        local-dir: ./                  
        server-dir: ./public_html/